/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    "./src/styles/**/*.css",
  ],
  theme: {
    extend: {
      colors: {
        'dark-bg': '#121212',
        'light-bg': '#f4f4f4',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      animation: {
        blink: 'blink 1s step-end infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 6s ease-in-out infinite',
        'slide-in': 'slideIn 0.6s forwards',
        'spin': 'spin 1s linear infinite',
        'fadeIn': 'fadeIn 0.7s ease-in-out forwards',
        'loadingBar': 'loadingBar 1.5s infinite',
        heartbeat: 'heartbeat 1.5s ease-in-out infinite',
      },
      keyframes: {
        blink: {
          '0%, 100%': { opacity: 1 },
          '50%': { opacity: 0 },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        slideIn: {
          '0%': { transform: 'translateY(20px)', opacity: 0 },
          '100%': { transform: 'translateY(0)', opacity: 1 },
        },
        fadeIn: {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
        loadingBar: {
          '0%': { left: '-100%', width: '100%' },
          '100%': { left: '100%', width: '100%' },
        },
        heartbeat: {
          '0%': { transform: 'scale(1)' },
          '14%': { transform: 'scale(1.3)' },
          '28%': { transform: 'scale(1)' },
          '42%': { transform: 'scale(1.3)' },
          '70%': { transform: 'scale(1)' },
        },
      },
      boxShadow: {
        'inner-lg': 'inset 0 2px 10px 0 rgba(0, 0, 0, 0.2)',
        'glow': '0 0 20px rgba(59, 130, 246, 0.5)',
      },
      backdropFilter: {
        'none': 'none',
        'blur': 'blur(8px)',
      },
    },
  },
  plugins: [],
  safelist: [
    'from-blue-500',
    'to-teal-400',
    'from-purple-500/20',
    'to-blue-500/20',
    'from-teal-500/20',
    'to-cyan-500/20',
    'from-orange-500/20',
    'to-amber-500/20',
    'hover:text-gray-900',
    'hover:text-[#0077B5]',
    'hover:text-[#E1306C]',
    'hover:text-[#1877F2]',
    'hover:text-[#25D366]',
    'hover:bg-gray-200/30',
    'dark:hover:bg-gray-700/50',
    'hover:bg-blue-100/50',
    'dark:hover:bg-blue-900/30',
    'hover:bg-pink-100/50',
    'dark:hover:bg-pink-900/30',
    'hover:bg-blue-100/50',
    'dark:hover:bg-blue-800/30',
    'hover:bg-green-100/50',
    'dark:hover:bg-green-900/30',
    'text-gray-700',
    'dark:text-gray-300',
    'text-blue-600',
    'dark:text-blue-400',
    'text-pink-600',
    'dark:text-pink-400',
    'text-blue-700',
    'dark:text-blue-500',
    'text-green-600',
    'dark:text-green-400',
  ]
};
